language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn install

script:
  - npm run test

after_script:
  - npm run codecov
  - cat ./coverage/lcov.info | coveralls -repotoken $COVERALLS_TOKEN
