language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn install

script:
  - npm run test && npm run codecov && npm run coveralls
